- name: Update apt cache
  apt:
    update_cache: yes

# Install dependencies
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - apt-transport-https
  - software-properties-common
  - wget

# Add Grafana GPG key
- name: Add Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: yes

# Install Grafana
- name: Install Grafana
  apt:
    name: grafana
    state: present
