---
 - name: application loading
   hosts: dev
   become: true
   roles: 
     - flask
     - snmpd
     - prometheus_node

 - name: loadbalancer
   hosts: proxy
   become: true
   roles:
     - haproxy
     - keepalived
     - ngnix
     - prometheus_node





