---
 - name: application loading
   hosts: dev
   become: true
   roles: 
     - flask
     - snmpd

 - name: loadbalancer
   hosts: proxy
   become: true
   roles:
     - haproxy
     - keepalived
     - ngnix





