- name: copy template
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0744
    owner: root
    group: root

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started

