- name: Copy Keepalived configuration for proxy_1
  template:
    src: keepalived.proxy_1.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
    owner: root
    group: root
  when: inventory_hostname == 'proxy_1'
  notify: Restart Keepalived Service

- name: Copy Keepalived configuration for proxy_2
  template:
    src: keepalived.proxy_2.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
    owner: root
    group: root
  when: inventory_hostname == 'proxy_2'
  notify: Restart Keepalived Service

- name: Copy Keepalived configuration for proxy_2
  template:
    src: scripts.sh.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
    owner: root
    group: root
  when: inventory_hostname == 'proxy_2'
  notify: Restart Keepalived Service

- name: copy openstack file to proxy server
  copy:
    src: openrcfile
    dest: /opt/openrcfile
    mode: '0644'
    owner: root
    group: root

