- name: Install Ansible and required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - ansible
  - zip
  - unzip

- name: Copy Ansible folder to bastion
  copy:
    src: NSO_final_project.zip
    dest: /opt/
    owner: root
    group: root
    mode: '0755'

- name: Unzip the archive
  shell: unzip /opt/NSO_final_project.zip

- name: Print bastion and proxy IP addresses
  debug:
    msg: "This is the bastion IP address: {{ floatingIp.bastion }} and proxy IP: {{ floatingIp.haproxy }}"


